/**
 * Comprehensive worldwide job title list for job search autocomplete.
 * Covers software, data, AI/ML, product, design, DevOps, security,
 * marketing, sales, finance, HR, legal, operations, healthcare, and more.
 */
export const JOB_TITLES: string[] = [

  // ── Software Engineering ──────────────────────────────────────────────────
  'Software Engineer',
  'Junior Software Engineer',
  'Associate Software Engineer',
  'Mid-level Software Engineer',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Principal Software Engineer',
  'Lead Software Engineer',
  'Distinguished Engineer',
  'Fellow',
  'Software Developer',
  'Junior Software Developer',
  'Senior Software Developer',
  'Software Architect',
  'Senior Software Architect',
  'Principal Architect',
  'Enterprise Architect',
  'Solutions Architect',
  'Technical Architect',
  'Application Developer',
  'Application Engineer',
  'Systems Engineer',
  'Systems Programmer',
  'Systems Developer',

  // ── Frontend ──────────────────────────────────────────────────────────────
  'Frontend Engineer',
  'Junior Frontend Engineer',
  'Senior Frontend Engineer',
  'Staff Frontend Engineer',
  'Principal Frontend Engineer',
  'Frontend Developer',
  'Senior Frontend Developer',
  'UI Engineer',
  'UI Developer',
  'Web Developer',
  'Junior Web Developer',
  'Senior Web Developer',
  'Web Application Developer',
  'React Developer',
  'Senior React Developer',
  'Next.js Developer',
  'Vue.js Developer',
  'Angular Developer',
  'Svelte Developer',
  'TypeScript Developer',
  'JavaScript Developer',
  'HTML/CSS Developer',
  'WordPress Developer',
  'Drupal Developer',
  'Shopify Developer',
  'Magento Developer',
  'Webflow Developer',

  // ── Backend ───────────────────────────────────────────────────────────────
  'Backend Engineer',
  'Junior Backend Engineer',
  'Senior Backend Engineer',
  'Staff Backend Engineer',
  'Principal Backend Engineer',
  'Backend Developer',
  'Senior Backend Developer',
  'API Developer',
  'API Engineer',
  'Node.js Developer',
  'Node.js Engineer',
  'Python Developer',
  'Python Engineer',
  'Java Developer',
  'Java Engineer',
  'Go Developer',
  'Go Engineer',
  'Golang Developer',
  'Rust Developer',
  'Rust Engineer',
  'Ruby Developer',
  'Ruby on Rails Developer',
  'PHP Developer',
  'Laravel Developer',
  'C# Developer',
  '.NET Developer',
  'ASP.NET Developer',
  'C++ Developer',
  'C++ Engineer',
  'Scala Developer',
  'Kotlin Developer',
  'Spring Boot Developer',
  'Django Developer',
  'FastAPI Developer',
  'Elixir Developer',
  'Haskell Developer',
  'Clojure Developer',

  // ── Full Stack ────────────────────────────────────────────────────────────
  'Full Stack Engineer',
  'Junior Full Stack Engineer',
  'Senior Full Stack Engineer',
  'Staff Full Stack Engineer',
  'Full Stack Developer',
  'Senior Full Stack Developer',
  'MEAN Stack Developer',
  'MERN Stack Developer',
  'LAMP Stack Developer',

  // ── Mobile ────────────────────────────────────────────────────────────────
  'Mobile Engineer',
  'Senior Mobile Engineer',
  'Staff Mobile Engineer',
  'Mobile Developer',
  'Senior Mobile Developer',
  'iOS Engineer',
  'Junior iOS Engineer',
  'Senior iOS Engineer',
  'Staff iOS Engineer',
  'iOS Developer',
  'Senior iOS Developer',
  'Swift Developer',
  'Swift Engineer',
  'Objective-C Developer',
  'Android Engineer',
  'Junior Android Engineer',
  'Senior Android Engineer',
  'Staff Android Engineer',
  'Android Developer',
  'Senior Android Developer',
  'Kotlin Android Developer',
  'React Native Developer',
  'React Native Engineer',
  'Flutter Developer',
  'Flutter Engineer',
  'Xamarin Developer',
  'Cross-Platform Mobile Developer',

  // ── Data Engineering & Analytics ──────────────────────────────────────────
  'Data Engineer',
  'Junior Data Engineer',
  'Senior Data Engineer',
  'Staff Data Engineer',
  'Principal Data Engineer',
  'Lead Data Engineer',
  'Data Architect',
  'Data Warehouse Engineer',
  'ETL Developer',
  'ETL Engineer',
  'Analytics Engineer',
  'Data Pipeline Engineer',
  'Big Data Engineer',
  'Spark Engineer',
  'Kafka Engineer',
  'Databricks Engineer',
  'Snowflake Engineer',
  'dbt Developer',
  'Data Analyst',
  'Junior Data Analyst',
  'Senior Data Analyst',
  'Staff Data Analyst',
  'Business Analyst',
  'Senior Business Analyst',
  'Business Intelligence Analyst',
  'BI Developer',
  'BI Engineer',
  'Tableau Developer',
  'Power BI Developer',
  'Looker Developer',
  'Quantitative Analyst',
  'Database Administrator',
  'DBA',
  'SQL Developer',
  'Database Developer',
  'Database Engineer',
  'Data Quality Engineer',
  'Data Governance Analyst',

  // ── Data Science ──────────────────────────────────────────────────────────
  'Data Scientist',
  'Junior Data Scientist',
  'Senior Data Scientist',
  'Staff Data Scientist',
  'Principal Data Scientist',
  'Lead Data Scientist',
  'Research Data Scientist',
  'Applied Data Scientist',
  'Computational Scientist',
  'Statistician',
  'Biostatistician',
  'Quantitative Researcher',

  // ── AI / Machine Learning ─────────────────────────────────────────────────
  'Machine Learning Engineer',
  'Junior ML Engineer',
  'Senior ML Engineer',
  'Staff ML Engineer',
  'Principal ML Engineer',
  'Lead ML Engineer',
  'ML Researcher',
  'ML Scientist',
  'AI Engineer',
  'Senior AI Engineer',
  'Staff AI Engineer',
  'AI Researcher',
  'AI Scientist',
  'Applied Scientist',
  'Senior Applied Scientist',
  'Principal Applied Scientist',
  'Research Scientist',
  'Senior Research Scientist',
  'Principal Research Scientist',
  'Research Engineer',
  'Senior Research Engineer',
  'Deep Learning Engineer',
  'Computer Vision Engineer',
  'NLP Engineer',
  'Natural Language Processing Engineer',
  'Conversational AI Engineer',
  'Speech Engineer',
  'Speech Recognition Engineer',
  'Recommendation Systems Engineer',
  'MLOps Engineer',
  'ML Platform Engineer',
  'AI Infrastructure Engineer',
  'LLM Engineer',
  'Generative AI Engineer',
  'Prompt Engineer',
  'AI Product Engineer',
  'Reinforcement Learning Engineer',
  'Robotics Engineer',
  'Autonomous Systems Engineer',
  'Bioinformatics Engineer',
  'Computational Biologist',

  // ── DevOps / Platform / SRE ───────────────────────────────────────────────
  'DevOps Engineer',
  'Junior DevOps Engineer',
  'Senior DevOps Engineer',
  'Staff DevOps Engineer',
  'Principal DevOps Engineer',
  'Lead DevOps Engineer',
  'DevSecOps Engineer',
  'Platform Engineer',
  'Senior Platform Engineer',
  'Staff Platform Engineer',
  'Principal Platform Engineer',
  'Site Reliability Engineer',
  'Senior Site Reliability Engineer',
  'Staff Site Reliability Engineer',
  'SRE',
  'Infrastructure Engineer',
  'Senior Infrastructure Engineer',
  'Staff Infrastructure Engineer',
  'Cloud Engineer',
  'Senior Cloud Engineer',
  'Staff Cloud Engineer',
  'AWS Engineer',
  'GCP Engineer',
  'Azure Engineer',
  'Cloud Architect',
  'AWS Solutions Architect',
  'GCP Solutions Architect',
  'Azure Solutions Architect',
  'Kubernetes Engineer',
  'Kubernetes Administrator',
  'Docker Engineer',
  'Container Engineer',
  'Build Engineer',
  'Release Engineer',
  'CI/CD Engineer',
  'GitOps Engineer',
  'Terraform Engineer',
  'Ansible Engineer',
  'Linux Administrator',
  'Linux Engineer',
  'Systems Administrator',
  'Windows Administrator',
  'Network Engineer',
  'Network Administrator',
  'Network Architect',
  'Storage Engineer',
  'Virtualization Engineer',
  'VMware Engineer',

  // ── Security / Cybersecurity ──────────────────────────────────────────────
  'Security Engineer',
  'Junior Security Engineer',
  'Senior Security Engineer',
  'Staff Security Engineer',
  'Principal Security Engineer',
  'Cybersecurity Engineer',
  'Cybersecurity Analyst',
  'Information Security Analyst',
  'Information Security Engineer',
  'Application Security Engineer',
  'AppSec Engineer',
  'Cloud Security Engineer',
  'Network Security Engineer',
  'Security Architect',
  'Chief Information Security Officer',
  'CISO',
  'VP of Security',
  'Director of Security',
  'Head of Security',
  'Penetration Tester',
  'Pen Tester',
  'Ethical Hacker',
  'Red Team Engineer',
  'Blue Team Engineer',
  'Purple Team Engineer',
  'SOC Analyst',
  'Threat Intelligence Analyst',
  'Incident Response Engineer',
  'Forensic Analyst',
  'Digital Forensics Analyst',
  'Vulnerability Researcher',
  'Security Researcher',
  'IAM Engineer',
  'Identity Engineer',
  'Zero Trust Architect',
  'GRC Analyst',
  'Risk Analyst',
  'Risk Manager',
  'Compliance Engineer',
  'Compliance Analyst',
  'Compliance Manager',
  'Privacy Engineer',
  'Data Privacy Officer',

  // ── QA / Testing ──────────────────────────────────────────────────────────
  'QA Engineer',
  'Junior QA Engineer',
  'Senior QA Engineer',
  'Staff QA Engineer',
  'Lead QA Engineer',
  'QA Automation Engineer',
  'Automation Test Engineer',
  'Software Test Engineer',
  'Software Tester',
  'QA Analyst',
  'Quality Assurance Analyst',
  'Test Lead',
  'QA Lead',
  'SDET',
  'Software Development Engineer in Test',
  'Performance Engineer',
  'Load Testing Engineer',
  'Test Architect',
  'Mobile QA Engineer',
  'Manual QA Engineer',

  // ── Embedded / Hardware ───────────────────────────────────────────────────
  'Embedded Software Engineer',
  'Embedded Systems Engineer',
  'Embedded Developer',
  'Firmware Engineer',
  'Firmware Developer',
  'Hardware Engineer',
  'Electrical Engineer',
  'Electronics Engineer',
  'FPGA Engineer',
  'VLSI Engineer',
  'ASIC Design Engineer',
  'RF Engineer',
  'Signal Processing Engineer',
  'PCB Designer',
  'PCB Engineer',
  'Power Electronics Engineer',
  'Mechatronics Engineer',
  'Automation Engineer',
  'PLC Programmer',
  'Control Systems Engineer',
  'SCADA Engineer',
  'IoT Engineer',
  'IoT Developer',
  'Edge Computing Engineer',

  // ── Blockchain / Web3 ─────────────────────────────────────────────────────
  'Blockchain Developer',
  'Blockchain Engineer',
  'Smart Contract Developer',
  'Smart Contract Engineer',
  'Solidity Developer',
  'Solidity Engineer',
  'Web3 Developer',
  'Web3 Engineer',
  'DeFi Developer',
  'DeFi Engineer',
  'NFT Developer',
  'Crypto Engineer',
  'Crypto Analyst',
  'Tokenomics Analyst',

  // ── Game Development ──────────────────────────────────────────────────────
  'Game Developer',
  'Game Engineer',
  'Game Programmer',
  'Unity Developer',
  'Unity Engineer',
  'Unreal Engine Developer',
  'Unreal Engine Engineer',
  'Game Designer',
  'Level Designer',
  'Game Artist',
  'Technical Artist',
  '3D Artist',
  '3D Animator',
  'VR Developer',
  'AR Developer',
  'XR Developer',
  'Metaverse Developer',

  // ── Product Management ────────────────────────────────────────────────────
  'Product Manager',
  'Associate Product Manager',
  'APM',
  'Junior Product Manager',
  'Senior Product Manager',
  'Staff Product Manager',
  'Principal Product Manager',
  'Group Product Manager',
  'Director of Product',
  'Director of Product Management',
  'VP of Product',
  'VP of Product Management',
  'SVP of Product',
  'Chief Product Officer',
  'CPO',
  'Head of Product',
  'Product Lead',
  'Technical Product Manager',
  'Growth Product Manager',
  'Platform Product Manager',
  'Consumer Product Manager',
  'B2B Product Manager',
  'Enterprise Product Manager',
  'Product Owner',
  'Senior Product Owner',

  // ── Design / UX ──────────────────────────────────────────────────────────
  'Product Designer',
  'Junior Product Designer',
  'Senior Product Designer',
  'Staff Product Designer',
  'Principal Product Designer',
  'Lead Product Designer',
  'UX Designer',
  'Junior UX Designer',
  'Senior UX Designer',
  'Staff UX Designer',
  'UI Designer',
  'UI/UX Designer',
  'Senior UI/UX Designer',
  'Interaction Designer',
  'Visual Designer',
  'Senior Visual Designer',
  'Brand Designer',
  'Senior Brand Designer',
  'Graphic Designer',
  'Senior Graphic Designer',
  'Motion Designer',
  'Motion Graphics Designer',
  'Illustration Designer',
  'Design Systems Designer',
  'Design Engineer',
  'UX Researcher',
  'Senior UX Researcher',
  'User Researcher',
  'Mixed Methods Researcher',
  'UX Writer',
  'Senior UX Writer',
  'Content Designer',
  'Information Architect',
  'Service Designer',
  'Head of Design',
  'Design Director',
  'VP of Design',
  'Chief Design Officer',
  'CDO',
  '3D Designer',
  'Industrial Designer',
  'Interior Designer',
  'Fashion Designer',
  'Web Designer',
  'Senior Web Designer',

  // ── Engineering Leadership ────────────────────────────────────────────────
  'Engineering Manager',
  'Senior Engineering Manager',
  'Director of Engineering',
  'VP of Engineering',
  'SVP of Engineering',
  'EVP of Engineering',
  'CTO',
  'Chief Technology Officer',
  'Chief Architect',
  'Head of Engineering',
  'Head of Platform',
  'Head of Infrastructure',
  'Technical Director',
  'Technical Lead',
  'Tech Lead',
  'Engineering Lead',
  'Team Lead',

  // ── Program / Project Management ─────────────────────────────────────────
  'Program Manager',
  'Senior Program Manager',
  'Technical Program Manager',
  'TPM',
  'Senior TPM',
  'Staff TPM',
  'Director of Program Management',
  'VP of Program Management',
  'Project Manager',
  'Senior Project Manager',
  'IT Project Manager',
  'Technical Project Manager',
  'PMP',
  'Scrum Master',
  'Senior Scrum Master',
  'Agile Coach',
  'Release Train Engineer',
  'Portfolio Manager',
  'PMO Manager',

  // ── Developer Experience / Relations ──────────────────────────────────────
  'Developer Advocate',
  'Senior Developer Advocate',
  'Developer Relations Engineer',
  'DevRel Engineer',
  'Technical Evangelist',
  'Developer Experience Engineer',
  'DX Engineer',
  'Open Source Engineer',
  'Community Engineer',
  'Technical Community Manager',
  'Integration Engineer',
  'Implementation Engineer',
  'Technical Account Manager',
  'TAM',
  'Customer Solutions Engineer',
  'Partner Engineer',

  // ── Technical Writing / Documentation ────────────────────────────────────
  'Technical Writer',
  'Senior Technical Writer',
  'Staff Technical Writer',
  'Lead Technical Writer',
  'Documentation Engineer',
  'API Technical Writer',
  'Developer Documentation Specialist',
  'Knowledge Management Specialist',
  'Localization Engineer',
  'Technical Editor',

  // ── Sales ─────────────────────────────────────────────────────────────────
  'Sales Development Representative',
  'SDR',
  'Business Development Representative',
  'BDR',
  'Account Executive',
  'Junior Account Executive',
  'Senior Account Executive',
  'Mid-Market Account Executive',
  'Enterprise Account Executive',
  'Strategic Account Executive',
  'Named Account Executive',
  'Global Account Executive',
  'Account Manager',
  'Senior Account Manager',
  'Key Account Manager',
  'Strategic Account Manager',
  'Global Account Manager',
  'Sales Engineer',
  'Senior Sales Engineer',
  'Solutions Engineer',
  'Senior Solutions Engineer',
  'Pre-Sales Engineer',
  'Sales Manager',
  'Regional Sales Manager',
  'Area Sales Manager',
  'District Sales Manager',
  'Director of Sales',
  'VP of Sales',
  'SVP of Sales',
  'Chief Revenue Officer',
  'CRO',
  'Head of Sales',
  'Business Development Manager',
  'Senior Business Development Manager',
  'Director of Business Development',
  'VP of Business Development',
  'Head of Business Development',
  'Inside Sales Representative',
  'Outside Sales Representative',
  'Field Sales Representative',
  'Channel Sales Manager',
  'Partner Sales Manager',
  'Alliances Manager',
  'Sales Operations Manager',
  'Sales Operations Analyst',
  'Revenue Operations Manager',
  'Revenue Operations Analyst',
  'Sales Enablement Manager',
  'Sales Trainer',

  // ── Marketing ─────────────────────────────────────────────────────────────
  'Marketing Manager',
  'Senior Marketing Manager',
  'Director of Marketing',
  'VP of Marketing',
  'SVP of Marketing',
  'Chief Marketing Officer',
  'CMO',
  'Head of Marketing',
  'Digital Marketing Manager',
  'Digital Marketing Specialist',
  'Performance Marketing Manager',
  'Paid Media Manager',
  'PPC Specialist',
  'SEM Specialist',
  'SEO Specialist',
  'SEO Manager',
  'SEO Analyst',
  'Content Marketing Manager',
  'Content Marketer',
  'Content Strategist',
  'Social Media Manager',
  'Social Media Specialist',
  'Social Media Coordinator',
  'Community Manager',
  'Influencer Marketing Manager',
  'Email Marketing Specialist',
  'Email Marketing Manager',
  'Growth Marketer',
  'Growth Manager',
  'Growth Engineer',
  'Growth Hacker',
  'Product Marketing Manager',
  'Senior Product Marketing Manager',
  'Director of Product Marketing',
  'VP of Product Marketing',
  'Brand Manager',
  'Brand Strategist',
  'Brand Marketing Manager',
  'Marketing Analyst',
  'Marketing Data Analyst',
  'Demand Generation Manager',
  'Lead Generation Specialist',
  'Field Marketing Manager',
  'Event Marketing Manager',
  'Communications Manager',
  'PR Manager',
  'Public Relations Specialist',
  'Public Relations Manager',
  'Corporate Communications Manager',
  'Marketing Operations Manager',
  'Marketing Coordinator',
  'Marketing Associate',
  'Affiliate Marketing Manager',
  'CRM Manager',
  'Lifecycle Marketing Manager',
  'Retention Marketing Manager',

  // ── Customer Success / Support ────────────────────────────────────────────
  'Customer Success Manager',
  'Junior Customer Success Manager',
  'Senior Customer Success Manager',
  'Enterprise Customer Success Manager',
  'Strategic Customer Success Manager',
  'Director of Customer Success',
  'VP of Customer Success',
  'Head of Customer Success',
  'Customer Success Lead',
  'Customer Success Analyst',
  'Customer Success Operations Manager',
  'Customer Experience Manager',
  'Customer Experience Specialist',
  'Customer Support Engineer',
  'Technical Support Engineer',
  'Senior Technical Support Engineer',
  'Customer Support Specialist',
  'Customer Support Representative',
  'Customer Service Representative',
  'Customer Service Manager',
  'Help Desk Technician',
  'IT Support Specialist',
  'IT Support Analyst',
  'Service Desk Analyst',
  'Implementation Manager',
  'Onboarding Manager',
  'Onboarding Specialist',
  'Renewals Manager',
  'Account Renewal Manager',

  // ── Finance / Accounting ──────────────────────────────────────────────────
  'Financial Analyst',
  'Junior Financial Analyst',
  'Senior Financial Analyst',
  'Staff Financial Analyst',
  'Financial Controller',
  'Controller',
  'VP of Finance',
  'CFO',
  'Chief Financial Officer',
  'Director of Finance',
  'Head of Finance',
  'FP&A Analyst',
  'FP&A Manager',
  'Director of FP&A',
  'Accountant',
  'Senior Accountant',
  'CPA',
  'Management Accountant',
  'Cost Accountant',
  'Tax Analyst',
  'Tax Specialist',
  'Tax Manager',
  'Tax Accountant',
  'Bookkeeper',
  'Payroll Specialist',
  'Payroll Manager',
  'Payroll Analyst',
  'Treasury Analyst',
  'Treasury Manager',
  'Budget Analyst',
  'Investment Analyst',
  'Private Equity Analyst',
  'Venture Capital Analyst',
  'Portfolio Manager',
  'Fund Manager',
  'Hedge Fund Analyst',
  'Actuary',
  'Underwriter',
  'Financial Advisor',
  'Wealth Manager',
  'Internal Auditor',
  'External Auditor',
  'Audit Manager',
  'Audit Director',
  'Chief Audit Executive',
  'Compliance Officer',
  'Compliance Specialist',
  'Anti-Money Laundering Analyst',
  'AML Analyst',
  'Credit Analyst',
  'Loan Officer',
  'Mortgage Specialist',

  // ── HR / People Operations ────────────────────────────────────────────────
  'HR Manager',
  'HR Business Partner',
  'HRBP',
  'Senior HRBP',
  'HR Generalist',
  'HR Specialist',
  'HR Coordinator',
  'HR Analyst',
  'HR Operations Manager',
  'HR Operations Specialist',
  'Director of Human Resources',
  'VP of Human Resources',
  'VP of People',
  'Chief People Officer',
  'Head of HR',
  'Head of People',
  'Head of People Operations',
  'Recruiter',
  'Technical Recruiter',
  'Senior Recruiter',
  'Senior Technical Recruiter',
  'Lead Recruiter',
  'Executive Recruiter',
  'Campus Recruiter',
  'Talent Acquisition Manager',
  'Senior Talent Acquisition Manager',
  'Director of Talent Acquisition',
  'Head of Talent Acquisition',
  'Talent Acquisition Specialist',
  'Sourcer',
  'Technical Sourcer',
  'Compensation Analyst',
  'Compensation Manager',
  'Total Rewards Manager',
  'Benefits Specialist',
  'Benefits Manager',
  'Learning & Development Manager',
  'L&D Specialist',
  'Training Manager',
  'Organizational Development Manager',
  'Culture Manager',
  'Employee Experience Manager',
  'Employee Relations Manager',
  'Workforce Planning Analyst',
  'HRIS Analyst',
  'Workday Analyst',

  // ── Legal / Compliance ────────────────────────────────────────────────────
  'General Counsel',
  'VP of Legal',
  'Associate General Counsel',
  'Deputy General Counsel',
  'Corporate Counsel',
  'Senior Corporate Counsel',
  'Legal Counsel',
  'In-house Counsel',
  'Contract Manager',
  'Contract Specialist',
  'Contracts Analyst',
  'Paralegal',
  'Legal Assistant',
  'Legal Operations Manager',
  'Legal Operations Analyst',
  'Privacy Counsel',
  'Data Privacy Officer',
  'DPO',
  'Intellectual Property Counsel',
  'IP Counsel',
  'Patent Attorney',
  'Employment Counsel',
  'Litigation Counsel',

  // ── Operations / Strategy ─────────────────────────────────────────────────
  'Operations Manager',
  'Senior Operations Manager',
  'Director of Operations',
  'VP of Operations',
  'COO',
  'Chief Operating Officer',
  'Head of Operations',
  'Business Operations Manager',
  'Business Operations Analyst',
  'Strategy Manager',
  'Strategy Analyst',
  'Senior Strategy Analyst',
  'Director of Strategy',
  'VP of Strategy',
  'Chief of Staff',
  'Chief of Staff to CEO',
  'Management Consultant',
  'Strategy Consultant',
  'Associate Consultant',
  'Senior Consultant',
  'Principal Consultant',
  'IT Consultant',
  'Technology Consultant',
  'Business Consultant',
  'Salesforce Consultant',
  'SAP Consultant',
  'Oracle Consultant',
  'Workday Consultant',
  'ServiceNow Consultant',

  // ── Supply Chain / Logistics ──────────────────────────────────────────────
  'Supply Chain Manager',
  'Supply Chain Analyst',
  'Supply Chain Engineer',
  'Director of Supply Chain',
  'VP of Supply Chain',
  'Head of Supply Chain',
  'Logistics Manager',
  'Logistics Coordinator',
  'Logistics Analyst',
  'Procurement Manager',
  'Procurement Analyst',
  'Procurement Specialist',
  'Strategic Sourcing Manager',
  'Category Manager',
  'Buyer',
  'Senior Buyer',
  'Inventory Manager',
  'Inventory Analyst',
  'Demand Planner',
  'Supply Planner',
  'Warehouse Manager',
  'Fulfillment Manager',
  'Operations Coordinator',
  'Import/Export Specialist',
  'Customs Specialist',
  'Freight Coordinator',
  'Transportation Manager',
  'Fleet Manager',
  'Last Mile Delivery Manager',

  // ── Content / Media / Writing ─────────────────────────────────────────────
  'Content Writer',
  'Senior Content Writer',
  'Technical Writer',
  'Copywriter',
  'Senior Copywriter',
  'Creative Copywriter',
  'Copy Editor',
  'Content Editor',
  'Editor',
  'Managing Editor',
  'Executive Editor',
  'Editorial Director',
  'Journalist',
  'Reporter',
  'Content Strategist',
  'Content Manager',
  'Head of Content',
  'VP of Content',
  'UX Writer',
  'Content Designer',
  'Grant Writer',
  'Ghostwriter',
  'Video Producer',
  'Senior Video Producer',
  'Video Editor',
  'Senior Video Editor',
  'Cinematographer',
  'Videographer',
  'Podcast Producer',
  'Podcast Editor',
  'Creative Director',
  'Art Director',
  'Creative Lead',
  'Head of Creative',
  'VP of Creative',
  'Chief Creative Officer',
  'Multimedia Designer',
  'Presentation Designer',
  'Photo Editor',
  'Photographer',

  // ── Healthcare / Medical (tech-adjacent) ──────────────────────────────────
  'Healthcare IT Analyst',
  'Health Informatics Analyst',
  'Clinical Data Manager',
  'Clinical Research Associate',
  'CRA',
  'Clinical Research Coordinator',
  'Regulatory Affairs Specialist',
  'Regulatory Affairs Manager',
  'Pharmacovigilance Specialist',
  'Medical Affairs Manager',
  'Medical Writer',
  'Biomedical Engineer',
  'Clinical Engineer',
  'Healthcare Consultant',
  'Medical Device Engineer',
  'Health Technology Specialist',
  'Telehealth Specialist',
  'EHR Specialist',
  'Epic Analyst',
  'Cerner Analyst',
  'Digital Health Manager',
  'Patient Experience Manager',
  'Healthcare Operations Manager',
  'Hospital Administrator',
  'Nurse',
  'Registered Nurse',
  'Nurse Practitioner',
  'Physician',
  'Doctor',
  'Surgeon',
  'Radiologist',
  'Pharmacist',
  'Dentist',
  'Physiotherapist',
  'Occupational Therapist',
  'Speech Therapist',
  'Mental Health Counselor',
  'Psychiatrist',
  'Psychologist',
  'Medical Laboratory Scientist',
  'Laboratory Technician',

  // ── Education / EdTech ────────────────────────────────────────────────────
  'Curriculum Developer',
  'Instructional Designer',
  'Senior Instructional Designer',
  'E-Learning Developer',
  'E-Learning Designer',
  'Learning Experience Designer',
  'LXD',
  'Education Technology Specialist',
  'EdTech Developer',
  'Corporate Trainer',
  'Training Specialist',
  'Training Manager',
  'Director of Learning & Development',
  'Chief Learning Officer',
  'CLO',
  'Teacher',
  'Lecturer',
  'Professor',
  'Academic Researcher',
  'Tutor',
  'Education Coordinator',
  'School Counselor',

  // ── Research / Science ────────────────────────────────────────────────────
  'Research Scientist',
  'Senior Research Scientist',
  'Principal Research Scientist',
  'Research Engineer',
  'Senior Research Engineer',
  'Principal Research Engineer',
  'Scientist',
  'Senior Scientist',
  'Principal Scientist',
  'Data Scientist', // covered but common here too
  'Chemist',
  'Chemical Engineer',
  'Materials Scientist',
  'Materials Engineer',
  'Environmental Scientist',
  'Environmental Engineer',
  'Geologist',
  'Geophysicist',
  'Physicist',
  'Mathematician',
  'Neuroscientist',
  'Cognitive Scientist',
  'Biological Scientist',
  'Biomedical Scientist',
  'Lab Scientist',
  'R&D Engineer',
  'R&D Scientist',
  'Product Development Engineer',
  'Process Engineer',
  'Test Engineer',
  'Validation Engineer',

  // ── Non-profit / Government / Public Sector ────────────────────────────────
  'Program Coordinator',
  'Program Manager', // covered
  'Program Director',
  'Policy Analyst',
  'Policy Manager',
  'Policy Advisor',
  'Government Affairs Manager',
  'Public Affairs Manager',
  'Community Outreach Coordinator',
  'Community Organizer',
  'Nonprofit Manager',
  'Executive Director (Nonprofit)',
  'Development Director (Nonprofit)',
  'Fundraising Manager',
  'Grant Manager',

  // ── Architecture / Civil / Construction ────────────────────────────────────
  'Architect',
  'Senior Architect',
  'Principal Architect',
  'Civil Engineer',
  'Structural Engineer',
  'Mechanical Engineer',
  'Senior Mechanical Engineer',
  'Aerospace Engineer',
  'Aviation Engineer',
  'Marine Engineer',
  'Nuclear Engineer',
  'Chemical Process Engineer',
  'Manufacturing Engineer',
  'Industrial Engineer',
  'Quality Engineer',
  'Construction Manager',
  'Project Engineer',
  'Site Engineer',
  'BIM Manager',
  'BIM Coordinator',
  'Urban Planner',
  'Transportation Engineer',

  // ── Real Estate ────────────────────────────────────────────────────────────
  'Real Estate Analyst',
  'Real Estate Manager',
  'Property Manager',
  'Asset Manager',
  'Portfolio Manager', // covered above
  'Real Estate Investment Analyst',
  'REIT Analyst',
  'Commercial Real Estate Broker',

  // ── Retail / E-commerce ────────────────────────────────────────────────────
  'E-commerce Manager',
  'E-commerce Specialist',
  'Marketplace Manager',
  'Amazon Marketplace Manager',
  'Merchandising Manager',
  'Category Manager', // covered
  'Retail Operations Manager',
  'Store Manager',
  'Visual Merchandiser',
  'Pricing Analyst',
  'Pricing Manager',

  // ── Hospitality / Food / Travel ────────────────────────────────────────────
  'Hotel Manager',
  'Restaurant Manager',
  'Food & Beverage Manager',
  'Chef',
  'Executive Chef',
  'Hospitality Manager',
  'Travel Manager',
  'Tourism Manager',
  'Event Manager',
  'Event Planner',
  'Event Coordinator',
  'Wedding Planner',

  // ── Administrative ────────────────────────────────────────────────────────
  'Executive Assistant',
  'Senior Executive Assistant',
  'Administrative Assistant',
  'Office Manager',
  'Personal Assistant',
  'Chief of Staff', // covered
  'Receptionist',
  'Administrative Coordinator',
  'Virtual Assistant',
  'Office Administrator',

  // ── C-Suite / Executive ────────────────────────────────────────────────────
  'CEO',
  'Chief Executive Officer',
  'President',
  'COO',
  'Chief Operating Officer',
  'CFO',
  'Chief Financial Officer',
  'CTO',
  'Chief Technology Officer',
  'CPO',
  'Chief Product Officer',
  'CMO',
  'Chief Marketing Officer',
  'CRO',
  'Chief Revenue Officer',
  'CISO',
  'Chief Information Security Officer',
  'CIO',
  'Chief Information Officer',
  'CHRO',
  'Chief Human Resources Officer',
  'CLO',
  'Chief Legal Officer',
  'General Counsel',
  'CDO',
  'Chief Data Officer',
  'Chief AI Officer',
  'CAIO',
  'Chief Analytics Officer',
  'Chief Customer Officer',
  'Chief Experience Officer',
  'Chief Growth Officer',
  'Chief of Staff',
  'Managing Director',
  'General Manager',
  'Country Manager',
  'Regional Manager',
  'Division President',
  'EVP',
  'Executive Vice President',
  'SVP',
  'Senior Vice President',
  'VP',
  'Vice President',
  'Group Director',
  'Senior Director',
  'Director',
  'Associate Director',
  'Principal',

  // ── Internships / Entry-level ─────────────────────────────────────────────
  'Software Engineering Intern',
  'Data Science Intern',
  'Product Management Intern',
  'Design Intern',
  'Marketing Intern',
  'Business Development Intern',
  'Finance Intern',
  'HR Intern',
  'Operations Intern',
  'Research Intern',
  'Engineering Intern',
  'DevOps Intern',
  'ML Intern',
  'AI Intern',
  'Sales Intern',
  'Customer Success Intern',
  'Content Writing Intern',
  'Analyst Intern',
  'Investment Banking Analyst',
  'Management Trainee',
  'Graduate Trainee',
  'Fresher',
  'Entry Level Developer',
  'Entry Level Engineer',
  'Entry Level Analyst',

  // ── Freelance / Contract ──────────────────────────────────────────────────
  'Freelance Developer',
  'Freelance Designer',
  'Freelance Writer',
  'Freelance Consultant',
  'Contract Software Engineer',
  'Contract Data Scientist',
  'Contract Developer',
  'Independent Consultant',
];
